@startuml
title Логика бота: Выбор следующего хода

start

:Определить, есть ли предыдущий ход?;
if (Первый ход?) then (да)
  :Выбрать "Камень";
  :Запомнить выбор;
  stop
endif

:Определить результат предыдущей схватки;
if (Выиграл или ничья?) then (да)
  :Использовать стратегию победы;
  if (Последний ход = "Камень"?) then (да)
    :Следующий ход = "Ножницы";
  elseif (Последний ход = "Ножницы"?) then (да)
    :Следующий ход = "Бумага";
  else (Последний ход = "Бумага")
    :Следующий ход = "Камень";
  endif
else (Проиграл)
  if (Противник не знает методику?) then (да)
    :Применить ту же стратегию, что и при выигрыше;
    if (Последний ход = "Камень"?) then (да)
      :Следующий ход = "Ножницы";
    elseif (Последний ход = "Ножницы"?) then (да)
      :Следующий ход = "Бумага";
    else (Последний ход = "Бумага")
      :Следующий ход = "Камень";
    endif
  else (Противник знает методику)
    :Использовать альтернативную стратегию;
    if (Последний ход = "Камень"?) then (да)
      :Следующий ход = "Бумага";
    elseif (Последний ход = "Ножницы"?) then (да)
      :Следующий ход = "Камень";
    else (Последний ход = "Бумага")
      :Следующий ход = "Ножницы";
    endif
  endif
endif

:Запомнить выбранный ход;
stop
@enduml

