@startuml
title Схема: overall_prediction

:Нач. установк;
:Проверить ист.;

if ("Ист. пуста?") then (Да)
  :Вернуть None;
  stop
endif

:Уст. СЧ = {К:0 Б:0 Н:0};
:Подсчитать ходы;
:Опред. макс СЧ;
:Вернуть ход;
stop
@enduml
