@startuml SA_Определить_контрход
title SA: контрход
start
:НУ: Уст. входные;
if (рез = win?) then (Да)
  :Применить Правл A;
  note right
    Правл A:
    Камень→Ножницы
    Ножницы→Бумага
    Бумага→Камень
  end note
  :Вернуть контрход;
else (Нет)
  if (ОКМ = Да?) then (Да)
    :Применить Правл B;
    note right
      Правл B:
      Камень→Бумага
      Ножницы→Камень
      Бумага→Ножницы
    end note
    :Вернуть контрход;
  else (Нет)
    :Применить Правл A;
    :Вернуть контрход;
  endif
endif
stop
@enduml
