@startuml
' Диаграмма алгоритма markov_prediction
title Markov Prediction Algorithm

start
:Проверить наличие предыдущего хода;
if (Нет предыдущего хода?) then (да)
  :Вызвать Overall Prediction;
  stop
endif
:Получить статистику переходов для предыдущего хода;
if (Нет данных переходов?) then (да)
  :Вызвать Overall Prediction;
  stop
endif
:Определить ход с наибольшим числом переходов;
:При равенстве выбрать ROCK по умолчанию;
:Вернуть предсказанный ход;
stop
@enduml