@startuml
' Диаграмма алгоритма overall_prediction
title Overall Prediction Algorithm

start
:Создать карту частот для ROCK, PAPER, SCISSORS;
:Проверить, есть ли данные в истории;
if (История пуста?) then (да)
  :Выбрать ROCK;
  stop
else (нет)
  :Определить ход с наибольшей частотой;
  :При равенстве выбрать ROCK по умолчанию;
  :Вернуть предсказанный ход;
  stop
endif
@enduml