@startuml
title Функция: Поиск паттернов

start
:Проверить историю;
if ("Мало ходов?") then (Да)
  :Общий анализ;
  stop
endif

:Уст. макс. паттерн;
:Уст. итерацию;

repeat
  :Выбрать паттерн;
  :Искать повтор;
  if ("Найден повтор?") then (Да)
    :Подсчитать ход;
    if ("Данные есть?") then (Да)
      :Выбрать ход;
      stop
    else (Нет)
      :След. паттерн;
    endif
  else (Нет)
    :След. паттерн;
  endif
repeat while ("Еще паттерн?")

:Общий анализ;
stop
@enduml
