@startuml
title Дерево решений: Ходы соперника (без условий)

[*] --> Камень : первый ход

Камень --> Ножницы : выиграл
Камень --> Бумага : проиграл
Камень --> Камень : ничья

Ножницы --> Бумага : выиграл
Ножницы --> Камень : проиграл
Ножницы --> Ножницы : ничья

Бумага --> Камень : выиграл
Бумага --> Ножницы : проиграл
Бумага --> Бумага : ничья
@enduml
