@startuml SA_choose
title SA: choose
start
:НУ: Уст. лок. пер.;
if (ПХС = 0?) then (Да)
  :Пропустить ПХС;
else
  :Добавить ПХС в МПХС;
endif
:Уст. N МПХС;
while (N > 0?) is (Да)
  :Собрать образец;
  :Проверить образец;
  if (Детермин?) then (Да)
    :Уст. ПРЕД = образец;
    :Уст. ОКМ = Да;
    :Прервать цикл;
    break
  else (Нет)
    :Ум. N;
  endif
endwhile
if (ПРЕД есть?) then (Да)
  :Вызвать контрход (win);
else (Нет)
  if (ПХ есть?) then (Нет)
    :Выбрать баз. ход;
  else (Да)
    :Опред. исход раунд;
    :Вызвать контрход (рез);
  endif
endif
:Уст. ПХ = выбран;
:return выбран;
stop
@enduml
