@startuml SA_Опред_детермин_детал
title SA: Опред. детермин.
start
:НУ: Уст. вход: ОБ, МПХС;
:НУ: Рез = детермин;
:НУ: Инд = 1;
:НУ: эталон = пусто;
while (След есть?) is (Да)
  :Найти след. по ОБ,МПХС,Инд;
  note right: "след." = ход сразу после ОБ
  if (Перв. проверка?) then (Да)
    :Уст. эталон = след.;
  else (Нет)
    :Сравнить след. с эталон;
    note right: "Сравнение след." = проверка равенства ходов
  endif
  if (Равны?) then (Да)
    :Ув. Инд;
    note right: "Ув. Инд" = увеличить Инд на 1;
  else (Нет)
    :Рез = недетермин;
    break
  endif
endwhile
:Вернуть Рез;
stop
@enduml

@startuml SA_Найти_след
title SA: Найти след.
start
:НУ: Уст. вход: ОБ, МПХС, Инд;
:Найти поз ОБ;
note right
  "Поз ОБ" = позиция ОБ в МПХС,
  для Инд-вхождения
end note
:Найти след. эл.;
note right
  "След." = эл. МПХС,
  сразу после "Поз ОБ"
end note
:Вернуть След.;
stop
@enduml

